### PR TITLE
compiled the submitBtn selector fix to dist/ folder

### PR DESCRIPTION
**Pull request by sheyooo**
copiled to emoji.min.js in dist/ folder due to @k-zakhariy fix

### CODE REVIEW

**Comment by madhur** [comment]
I dont't want to indroduce gulp as additional dependency. I am already using grunt as the build tool. See this branch:

https://github.com/Coraza/angular-emoji-popup/tree/gh-pages

**Comment by sheyooo** [comment]
@madhur  i am not familiar with grunt, should i push only the minified code and leave out.. Gulp so the only change would be the emoji.min.js. Because that is what needs the fix..

**Comment by madhur** [comment]
Give me some time, I will do it myself. Right now you can use the change in your own fork.

**Comment by sheyooo** [comment]
all right

**Pull request closed without merging**
