### PR TITLE
Fixed bug with submitBtn selector

### PR DESCRIPTION
**Pull request by k-zakhariy**

### CODE REVIEW

**Comment by k-zakhariy** [comment]
Please merge pull-request

**Comment by madhur** [comment]
Can you describe what is the purpose of this pull request ?

**Comment by k-zakhariy** [comment]
We use your library in our project, first of all - thanks a lot for it. And
we found a bug in code, there are one missing variable submitBtn that
throws an error;

2016-01-12 14:54 GMT+02:00 Madhur Ahuja <notifications@github.com>:

> Can you describe what is the purpose of this pull request ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Coraza/angular-emoji-popup/pull/28#issuecomment-170903238>
> .
>



-- 

*З повагою,*

*Захарій*

**Comment by madhur** [comment]
:+1:

**Comment by k-zakhariy** [comment]
Thanks! :blush:

**Comment by k-zakhariy** [comment]
When i try to pull new version , it pulls an old version, any ideas about this trouble ?
I tried with --force flag, and tried run 'bower cache clean' before, but no success
image

**Comment by madhur** [comment]
I am not aware of bower much. I think version needs to be incremented.

On Wed, Jan 13, 2016 at 2:46 PM, Zakhariy <notifications@github.com> wrote:

> When i try to pull new version , it pulls an old version, any ideas about
> this trouble ?
> I tried with --force flag, and tried run 'bower cache clean' before, but
> no success
> [image: image]
> <https://cloud.githubusercontent.com/assets/5267851/12289877/dd176e1a-b9e6-11e5-8be6-ebd615ce4c3f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Coraza/angular-emoji-popup/pull/28#issuecomment-171224225>
> .
>



-- 

Madhur
Senior Developer
9999 55 9848

**Comment by sheyooo** [comment]
this will be fixed in the latest pull request

**Comment by k-zakhariy** [comment]
How i can pull last changes ? When i run `bower update angular-emoji-popup -f --save`  i have an old code, and bug that i fixed is present .

**Comment by sheyooo** [comment]
@k-zakhariy the change is in the `src/` folder the changes need to be compiled into the `dist/` folder which i have done in a fork of my own and provided a pull request but the problem is the dependencies,, i used gulp for my compilation he uses grunt so he doesnt want to merge the one with gulp so you pull my fork or see it you can use grunt to compile the changes and ask for a merge

**Comment by k-zakhariy** [comment]
but here i dont see any changes in `src/`, and i build all this files with gulp already from src/
screenshot

**Comment by sheyooo** [comment]
`bower install https://github.com/sheyooo/angular-emoji-popup.git` thats my fork and its all fixed in my fork

**Comment by k-zakhariy** [comment]
I tried, it's also don't work
`d:\OpenServer\domains\test>bower cache clean
bower deleted       Cached package angular-emoji-popup: C:\Users\Admin\AppData\Local\bower\cache\packages\81e229f177f92993010bbcc631f03865\1.1.0

d:\OpenServer\domains\test>bower install https://github.com/sheyooo/angular-emoji-popup.git --save
bower angular-emoji-popup#* not-cached https://github.com/sheyooo/angular-emoji-popup.git#*
bower angular-emoji-popup#*    resolve https://github.com/sheyooo/angular-emoji-popup.git#*
bower angular-emoji-popup#*   checkout 1.1.0
bower angular-emoji-popup#*   mismatch Version declared in the json (0.0.0) is different than the resolved one (1.1.0)
bower angular-emoji-popup#*     invalid-meta angular-emoji-popup is missing "ignore" entry in bower.json
bower angular-emoji-popup#*         resolved https://github.com/sheyooo/angular-emoji-popup.git#1.1.0

d:\OpenServer\domains\test>`

after bower install i have an old version.

**Comment by sheyooo** [comment]
@k-zakhariy https://github.com/sheyooo/angular-emoji-popup thats my fork you can pull it directly with git or download the zip until madhur fixes it in his own repo,, he said he is busy

**Comment by madhur** [comment]
Will resolve all issues this week

**Pull request merged**
